# .goreleaser.yaml
builds:
  -
    goos:
      - darwin
      - dragonfly
      - freebsd
      - linux
      - netbsd
      - openbsd
      # - plan9
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - ppc64
      - ppc64le
      - riscv64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: ppc64
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: riscv64

      - goos: dragonfly
        goarch: 386
      - goos: dragonfly
        goarch: arm
      - goos: dragonfly
        goarch: arm64
      - goos: dragonfly
        goarch: ppc64
      - goos: dragonfly
        goarch: ppc64le
      - goos: dragonfly
        goarch: riscv64

      - goos: freebsd
        goarm: arm64
      - goos: freebsd
        goarm: ppc64
      - goos: freebsd
        goarm: ppc64le
      - goos: freebsd
        goarm: riscv64

      - goos: netbsd
        goarch: arm64
      - goos: netbsd
        goarch: ppc64
      - goos: netbsd
        goarch: ppc64le
      - goos: netbsd
        goarch: riscv64

      #- goos: plan9
      #  goarm: arm64
      #- goos: plan9
      #  goarm: ppc64
      #- goos: plan9
      #  goarm: ppc64le
      #- goos: plan9
      #  goarm: riscv64

      - goos: windows
        goarm: ppc64
      - goos: windows
        goarm: ppc64le
      - goos: windows
        goarm: riscv64

